name: Commit stage
on: push


jobs:
  test-actions:
    name: build and Test
    runs-on: ubuntu-22.6
    permissions:
      contents: read
      security-events: write
    steps:
      - name: 소스 체크 아웃
        uses: actions/checkout@v3
        
