name: Commit stage
on: push


jobs:
  test-actions:
    name: build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: 소스 체크 아웃
        uses: actions/checkout@v3
      - name: java 런타임 설치
        uses: actions/setup-java@3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle


        
