name: Commit stage
on: push


jobs:
  test-actions:
    name: build and Test
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      security-events: write
    steps:
      - name: 소스 체크 아웃
        uses: actions/checkout@v3

      - name: java 런타임 설치
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: 그라이프를 사용해 코드 스캔
        uses: anchore/scan-action@v3
        id: scan
        with:
          path: "{{github.workspace}}"
          fail-build: false
          severity-cutoff: high
          acs-report-enable: true

      - name: 업로드 보안 취약성 리포트로 작성
        uses: github/codeql-action/upload-sarif@v3
        #if: success() || failure()
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: results.json
          # Optional category for the results
          # Used to differentiate multiple results for one commit
          category: my-analysis-tool

      - name: 빌드 unit test 그리고 통합 테스트
        run: |
          chomd +x gradlew
          ./gradlew build        
          

        
